### ISSUE TITLE
Missing License Information

### ISSUE THREAD

**Issue by LlubNek** [shedaniel/SmoothScrollingEverywhere#14]
Forge now wants license garbage in every mod; it's not in yours so it errors out.
![image](https://user-images.githubusercontent.com/313762/103472029-1a60a680-4d56-11eb-841f-a0fb0f662e42.png)
```
[02Jan2021 23:47:11.833] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Missing License Information in file Mod File: C:\_gdl\instances\1.16.4-forge-20210102\mods\smooth-scrolling-everywhere-1.3.jar
	at net.minecraftforge.fml.ModLoader.lambda$new$4(ModLoader.java:121) ~[forge:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_242]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_242]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_242]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_242]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_242]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_242]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_242]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_242]
	at net.minecraftforge.fml.ModLoader.<init>(ModLoader.java:122) ~[forge:?]
	at net.minecraftforge.fml.ModLoader.get(ModLoader.java:148) ~[forge:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[forge:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[forge:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[forge:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:149) ~[1.16.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.28.jar:35.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
```

Also, there's a `NoSuchMethodException` (repeatedly) on the error screen:
```
[02Jan2021 23:56:42.722] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: java.lang.NoSuchMethodException: net.minecraft.client.gui.widget.list.AbstractList.getScrollbarPosition()
[02Jan2021 23:56:42.723] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: 	at java.lang.Class.getDeclaredMethod(Class.java:2130)
[02Jan2021 23:56:42.723] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: 	at me.shedaniel.smoothscrollingeverywhere.CustomAbstractList.renderScrollbar(CustomAbstractList.java:155)
[02Jan2021 23:56:42.723] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: 	at net.minecraft.client.gui.widget.list.AbstractList.func_230430_a_(AbstractList.java:227)
[02Jan2021 23:56:42.723] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: 	at net.minecraftforge.fml.client.gui.screen.LoadingErrorScreen.func_230430_a_(LoadingErrorScreen.java:103)
[02Jan2021 23:56:42.723] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:290)
[02Jan2021 23:56:42.723] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: 	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:491)
[02Jan2021 23:56:42.723] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976)
[02Jan2021 23:56:42.723] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
[02Jan2021 23:56:42.723] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: 	at net.minecraft.client.main.Main.main(Main.java:184)
[02Jan2021 23:56:42.723] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02Jan2021 23:56:42.723] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02Jan2021 23:56:42.723] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02Jan2021 23:56:42.723] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[02Jan2021 23:56:42.723] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[02Jan2021 23:56:42.723] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[02Jan2021 23:56:42.723] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[02Jan2021 23:56:42.723] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[02Jan2021 23:56:42.723] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[02Jan2021 23:56:42.723] [Render thread/INFO] [STDERR/]: [me.shedaniel.smoothscrollingeverywhere.CustomAbstractList:renderScrollbar:192]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
```
[2021-01-02-1.log.gz](https://github.com/shedaniel/SmoothScrollingEverywhere/files/5761231/2021-01-02-1.log.gz)
[crash-2021-01-02_23.47.17-fml.txt](https://github.com/shedaniel/SmoothScrollingEverywhere/files/5761230/crash-2021-01-02_23.47.17-fml.txt)

**Comment by MCOfficer** [comment]
I don't even know if this repository contains the forge version, so i can't send you a PR. Regardless, it's as simple as adding a `license` key to your mods.toml:

```toml
...
authors="shedaniel"
license="Apache-2.0"
[[mods]]
...
```
